version: '3.8' # or higher if needed

networks:
  app-network:
    driver: bridge
    ipam:
      config:
        - subnet: "172.28.0.0/16" # Define a subnet for the network

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - '8080:8080'
    depends_on:
      - postgres
    environment:
      DATABASE_URL: "postgres://postgres:postgres@172.28.0.2:5432/movies?sslmode=disable"
    networks:
      app-network:
        ipv4_address: 172.28.0.3
    logging:
      options:
        max-size: 10m
        max-file: "3"

  postgres:
    image: 'postgres:14.5'
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: movies
    ports:
      - '5432:5432'
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
      - ./sql/create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql
    networks:
      app-network:
        ipv4_address: 172.28.0.2
    logging:
      options:
        max-size: 10m
        max-file: "3"
